pretrained_model_name_or_path = "/home/buxinzi/Projects/toolbox/comfyui-image/ComfyUI/models/diffusion_models/Anima/anima-base-v1.0.safetensors"
qwen3 = "/home/buxinzi/Projects/toolbox/comfyui-image/ComfyUI/models/text_encoders/qwen_3_06b_base.safetensors"
vae = "/home/buxinzi/Projects/toolbox/comfyui-image/ComfyUI/models/vae/qwen_image_vae.safetensors"
test_prompt = "masterpiece, best quality, score_7, safe. An anime girl wearing a black tank-top and denim shorts is standing outdoors. She's holding a rectangular sign out in front of her that reads \"ANIMA\". She's looking at the viewer with a smile. The background features some trees and blue sky with clouds."
test_negative_prompt = "worst quality, low quality, score_1, score_2, score_3, blurry, jpeg artifacts, sepia"
output_dir = "output/ckpt"
output_name = "anima_lora"
save_model_as = "safetensors"
logging_dir = "output/logs"
training_comment = ""
log_with = "tensorboard"
network_module = "networks.lora_anima"
network_train_unet_only = true
resized_image_dir = "post_image_dataset/resized"
lora_cache_dir = "post_image_dataset/lora"
path_pattern = "*"
optimizer_type = "AdamW"
lr_scheduler = "constant"
timestep_sampling = "sigmoid"
sigmoid_scale = 1.3
sigmoid_bias = 0.0
discrete_flow_shift = 1.0
mixed_precision = "bf16"
gradient_checkpointing = false
unsloth_offload_checkpointing = false
use_vae_cache = true
use_text_cache = true
skip_cache_check = true
vae_chunk_size = 64
vae_disable_cache = true
masked_loss = true
torch_compile = true
attn_mode = "flash"
save_precision = "bf16"
compile_dynamic_seq = true
activation_memory_budget = 0.99
log_every_n_steps = 2
dataloader_pin_memory = true
persistent_data_loader_workers = false
use_cmmd = false
channel_scaling_alpha = 0.5
gradient_accumulation_steps = 1
use_repa = false
repa_target_dog = false
[[datasets]]
batch_size = 1
validation_split_num = 16
validation_seed = 42
[[datasets.subsets]]
image_dir = "{resized_image_dir}"
cache_dir = "{lora_cache_dir}"
num_repeats = 3
recursive = true

[preview]
sample_every_n_epochs = 5
sample_prompts = "configs/custom/sample_prompts.txt"
sample_sampler = "euler"
sample_guidance_scale = 3.5
sample_flow_shift = 1.0
sample_image_size = [ 1024, 1024,]

[general]
caption_extension = ".txt"

